// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDY4D6KUy-mV9vDn6b6eB7CVfhbZCk9ty0',
    appId: '1:129962059793:web:c91b78e7b0e641c3a129b0',
    messagingSenderId: '129962059793',
    projectId: 'hopehub-d7df0',
    authDomain: 'hopehub-d7df0.firebaseapp.com',
    storageBucket: 'hopehub-d7df0.firebasestorage.app',
    measurementId: 'G-CPTFDDD2K1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8udqUq9dTA01xq5Ql0fTdiSzvYg-M8vM',
    appId: '1:129962059793:android:6e2282a13bd7ba92a129b0',
    messagingSenderId: '129962059793',
    projectId: 'hopehub-d7df0',
    storageBucket: 'hopehub-d7df0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBg3A09eR5oaQRJIHeRVV3CfI_1RqrwVqQ',
    appId: '1:129962059793:ios:bdcd18ca224c1f32a129b0',
    messagingSenderId: '129962059793',
    projectId: 'hopehub-d7df0',
    storageBucket: 'hopehub-d7df0.firebasestorage.app',
    iosBundleId: 'com.example.flut1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBg3A09eR5oaQRJIHeRVV3CfI_1RqrwVqQ',
    appId: '1:129962059793:ios:bdcd18ca224c1f32a129b0',
    messagingSenderId: '129962059793',
    projectId: 'hopehub-d7df0',
    storageBucket: 'hopehub-d7df0.firebasestorage.app',
    iosBundleId: 'com.example.flut1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDY4D6KUy-mV9vDn6b6eB7CVfhbZCk9ty0',
    appId: '1:129962059793:web:72dead87b29bf581a129b0',
    messagingSenderId: '129962059793',
    projectId: 'hopehub-d7df0',
    authDomain: 'hopehub-d7df0.firebaseapp.com',
    storageBucket: 'hopehub-d7df0.firebasestorage.app',
    measurementId: 'G-LCXQFHWB88',
  );
}
